# Generated by Django 3.2.6 on 2021-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210901_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
    ]
