# Generated by Django 3.2.6 on 2021-09-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210901_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='first_name',
            new_name='Name',
        ),
    ]
