# Generated by Django 3.2.6 on 2021-09-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_first_name_feedback_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='Feedback',
        ),
    ]
