# Generated by Django 3.2.6 on 2021-09-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_feedback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='feedback',
        ),
    ]
