# Generated by Django 3.2.6 on 2021-09-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_text_feedback_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='first_name',
            new_name='name',
        ),
    ]
